import type { Metadata } from "next";
import "./globals.css";
import { createContext } from "react";
import ThemeProvider from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Project Feedback",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className="flex justify-center m-auto container mt-10">
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
