import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import ThemeProvider from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Project Feedback",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <ThemeProvider>
          <body className="md:flex justify-center m-auto md:container md:mt-10 overflow-hidden">
            {children}
          </body>
        </ThemeProvider>
      </html>
    </AuthProvider>
  );
}
